export const SERVICE_CATEGORIES = [
  "studio_bedsitter_cleaning",
  "one_bedroom_cleaning",
  "two_bedroom_cleaning",
  "three_plus_bedroom_cleaning",
  "kitchen_deep_cleaning",
  "bathroom_deep_cleaning",
  "sofa_upholstery_cleaning",
  "mattress_cleaning",
  "carpet_rug_cleaning",
  "balcony_outdoor_cleaning",
  "laundry_washing",
  "laundry_washing_ironing",
  "utensils_dishes_cleaning",
  "move_in_move_out_cleaning",
  "after_event_cleaning",
  "office_cleaning",
  "grocery_pickup",
  "parcel_delivery",
  "pharmacy_pickup",
  "house_supplies_purchase",
  "queue_bill_payment_errand",
  "document_dropoff_pickup",
  "delivery_transportation",
  "movers_services",
  "custom_errand",
  "salon_services",
  "barber_services",
  "babysitting_services",
  "pet_care_services",
  "plumbing_services",
  "electrical_services",
  "pest_control_services",
  "car_wash_services",
  "urgent_same_day_service",
  "bring_cleaning_supplies",
  "bring_tools_materials",
  "fragile_space_handling",
  "elderly_friendly_service",
  "pet_sensitive_cleaning",
  "night_early_morning_booking",

  "cleaning",
  "laundry",
  "errand",
  "delivery",
  "moving",
  "salon",
  "barber",
  "babysitting",
  "pet_care",
  "plumbing",
  "electrical",
  "pest_control",
  "car_wash"
];

export const SERVICE_CATEGORY_LABELS = {
  studio_bedsitter_cleaning: "Studio / Bedsitter Cleaning",
  one_bedroom_cleaning: "1 Bedroom House Cleaning",
  two_bedroom_cleaning: "2 Bedroom House Cleaning",
  three_plus_bedroom_cleaning: "3+ Bedroom House Cleaning",
  kitchen_deep_cleaning: "Kitchen Deep Cleaning",
  bathroom_deep_cleaning: "Bathroom Deep Cleaning",
  sofa_upholstery_cleaning: "Sofa / Upholstery Cleaning",
  mattress_cleaning: "Mattress Cleaning",
  carpet_rug_cleaning: "Carpet / Rug Cleaning",
  balcony_outdoor_cleaning: "Balcony / Outdoor Cleaning",
  laundry_washing: "Laundry Washing",
  laundry_washing_ironing: "Laundry Washing + Ironing",
  utensils_dishes_cleaning: "Utensils / Dishes Cleaning",
  move_in_move_out_cleaning: "Move-in / Move-out Cleaning",
  after_event_cleaning: "After-event Cleaning",
  office_cleaning: "Office Cleaning",
  grocery_pickup: "Grocery Pickup",
  parcel_delivery: "Parcel Delivery",
  pharmacy_pickup: "Pharmacy Pickup",
  house_supplies_purchase: "House Supplies Purchase",
  queue_bill_payment_errand: "Queue / Bill Payment Errand",
  document_dropoff_pickup: "Document Drop-off / Pickup",
  delivery_transportation: "Delivery Transportation",
  movers_services: "Movers Services",
  custom_errand: "Custom Errand",
  salon_services: "Salon Services",
  barber_services: "Barber Services",
  babysitting_services: "Babysitting Services",
  pet_care_services: "Pet Care Services",
  plumbing_services: "Plumbing Services",
  electrical_services: "Electrical Services",
  pest_control_services: "Pest Control Services",
  car_wash_services: "Car Wash Services",
  urgent_same_day_service: "Urgent Same-day Service",
  bring_cleaning_supplies: "Bring Cleaning Supplies",
  bring_tools_materials: "Bring Tools / Materials",
  fragile_space_handling: "Fragile-space Handling",
  elderly_friendly_service: "Elderly-friendly Service",
  pet_sensitive_cleaning: "Pet-sensitive Cleaning",
  night_early_morning_booking: "Night / Early-morning Booking",

  cleaning: "Cleaning",
  laundry: "Laundry",
  errand: "Errand",
  delivery: "Delivery",
  moving: "Moving",
  salon: "Salon Service",
  barber: "Barber Service",
  babysitting: "Babysitting",
  pet_care: "Pet Care",
  plumbing: "Plumbing",
  electrical: "Electrical",
  pest_control: "Pest Control",
  car_wash: "Car Wash"
};